"""table name changed

Revision ID: 7ffc6379bd5d
Revises: cc5b529fedbf
Create Date: 2026-02-10 20:18:46.424329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffc6379bd5d'
down_revision = 'cc5b529fedbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=200), nullable=False),
    sa.Column('maths', sa.Integer(), nullable=False),
    sa.Column('english', sa.Integer(), nullable=False),
    sa.Column('hindi', sa.Integer(), nullable=False),
    sa.Column('science', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('S_name', sa.String(length=100), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Students')
    op.drop_table('Subject')
    op.drop_table('Teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teacher',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Teacher_pkey')),
    sa.UniqueConstraint('email', name=op.f('Teacher_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('Subject',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('S_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.id'], name=op.f('Subject_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Subject_pkey'))
    )
    op.create_table('Students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('course', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('maths', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('english', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hindi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('science', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Students_pkey'))
    )
    op.drop_table('subjects')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
