"""Init

Revision ID: 95b6381e76b7
Revises: 
Create Date: 2026-02-06 19:24:05.419509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b6381e76b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.alter_column('maths',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('english',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hindi',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('science',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teacher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.alter_column('science',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hindi',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('english',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('maths',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
