"""neew addition

Revision ID: cc5b529fedbf
Revises: 95b6381e76b7
Create Date: 2026-02-06 21:02:58.213278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5b529fedbf'
down_revision = '95b6381e76b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.alter_column('S_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_foreign_key(None, 'Teacher', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('S_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
